# Generated by Django 5.0.6 on 2024-05-24 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0002_product_companyproduct_product_image"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("is_sub", models.BooleanField(default=False)),
                ("company_category", models.CharField(max_length=50, null=True)),
                ("slug", models.SlugField(unique=True)),
                (
                    "sub_category",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sub_categories",
                        to="app.category",
                    ),
                ),
            ],
        ),
    ]
