# Generated by Django 5.0.6 on 2024-05-24 09:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app", "0003_category"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="companyProduct",
        ),
        migrations.AddField(
            model_name="product",
            name="category",
            field=models.ManyToManyField(related_name="product", to="app.category"),
        ),
    ]
